- hosts: localhost
  vars_files:
    - "key.yml"

  tasks:
    - name: Create a security group
      ec2_group:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        name: "{{ security_group }}"
        region: "{{ region }}"
        state: present
        description: Create new Security Group
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          - proto: icmp
            from_port: 8 
            to_port:  -1
            cidr_ip: 0.0.0.0/0
          - proto: icmp
            from_port: 22
            to_port:  22
            cidr_ip: 0.0.0.0/0
          - proto: icmp
            from_port: 80
            to_port:  80
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: basic_firewall

    - name: Launch AWS EC2 Instance
      ec2:
        key_name: "{{ key_name }}"
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        instance_type: t2.micro
        image: "{{ ami }}"
        wait: yes
        group: "{{ security_group }}"
        count: 1
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet }}"
        assign_public_ip: yes
      register: ec2

     
  