- hosts: aws
  vars_files:
    - "users.yml"
  connection: ssh
  become: yes
  become_method: sudo
  gather_facts: no
  
    
  tasks:
    - name: create group admins
      group:
        name: admins
        state: present
    - name: Add users 
      user:
        name: "{{ item }}"
        groups: "admins"
        state: "{{ state }}"
      with_items: "{{ users }}"    
    - name: give sudo powers
      lineinfile:
        dest: "/etc/sudoers"
        state: "{{ state }}"
        regexp: "^%admin"
        line: "{{ item }} ALL=(ALL) NOPASSWD: ALL"
      with_items: "{{ users }}"
      when: state == "present"
    - name: Add authorized keys
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', 'ssh/'+ item + '.pub') }}"
      with_items: "{{ users }}"
      when: state == "present"
     
