- hosts: aws
  connection: ssh
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Add users 
      user:
        name: "{{ item }}"
        state: present
      with_items:
        - "john"
        - "ron"
    - name: give sudoe powers
      lineinfile:
        dest: "/etc/sudoers"
        state: present
        regexp: "^%admin"
        line: "{{ item }} ALL=(ALL) NOPASSWD: ALL"
      with_items:
        - "john"
        - "ron"

